spring.application.name=study-assistant-backend
server.servlet.context-path=/study-assistant/api

# Supabase Connection Settings
spring.datasource.url=jdbc:postgresql://<your-pooler-host>:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.projectUsername
spring.datasource.password=projectPassword
spring.datasource.driver-class-name=org.postgresql.Driver

# Supabase project url
supabase.project.url=supabaseProjectUrl

# Supabase Service Role Key
supabase.service-role-key=supabaseServiceRoleKey

# Supabase bucket settings
supabase.bucket.name=bucketName
supabase.storage.public-endpoint=storagePublicEndpoint

# Bootstrap email for first Admin creation
app.admin.bootstrap-email=admin@gmail.com

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# oauth issuer uri
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://projectUsername.supabase.co/auth/v1

# oauth debugging logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

# The JWT secret key and the jwt algorithm that will be used to verify the token coming from supabase (NOT NEEDED WHEN USING ISSUER URI)
#spring.security.oauth2.resourceserver.jwt.secret-key=jwtSecretKey
#jwt.algorithm=HS256

# Google API Key
google.api.key=googleAPIKey
google.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-embedding-2-preview:embedContent
google.chat.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent
